### ISSUE TITLE
Extend parameter identifiability analysis to nonlinear systems of ODEs

### ISSUE THREAD

**Issue by finmod** [insysbio/LikelihoodProfiler.jl#3]
An immediate reaction to the publication of the documentation for LikelihooProfiler is to consider from the very beginning nonlinear systems of ODEs as done in Matlab here :
https://bmcsystbiol.biomedcentral.com/articles/10.1186/s12918-017-0428-y

LikelihoodProfiler would be an excellent pure Julia version of the method in this reference and the algortithms involved are fully described. 

Concerning NLopt.jl, it is a good wrapper for NLopt in C. Today, a lot of this can be done in pure Julia with Optim or SparseDiffTools since you are already using JuliaDiffEq.

**Comment by ivborissov** [comment]
Thanks for the link!

If I understood correctly the article lists different approaches to system identification, while this package is mainly focused on developing Profile Likelihood approach described here
https://academic.oup.com/bioinformatics/article/25/15/1923/213246

Currently we use `NLopt` because it includes `AUGLAG` algorithm which allows us to combine objective function and constraints functions in to a single function. This modified objective function is "optimized" with derivative-free algorithms (`NELDERMEAD`, `COBYLA`) in a "single pass".

We have an example notebook of a PK model identification where we use `DiffEq` packages and we are looking forward to making bigger use-cases of this kind.
https://nbviewer.jupyter.org/github/insysbio/LikelihoodProfiler.jl/blob/master/notebook/pk_saturation.ipynb

We will be grateful to here from you of any ideas, use-cases that are useful to implement and  benchmark with `LikelihoodProfiler`

**Comment by metelkin** [comment]
Thanks @finmod for the feedback.
LikelihoodProfiler solves one particular problem: calculation of profile function characteristics as effectively as possible. The likelihood function as an argument can be based on ODEs or not, the algorithm uses an "abstract" form of it. Possibly we or others will develop the workflow for dynamic model solution and analysis based on LikelihoodProfiler but it will be another project.

> a lot of this can be done in pure Julia with Optim

Optim package does not include constraint optimization. We are not absolutely happy with NLopt but currently, but we have no simple solution to change the fitter. Anyway, Julia is friendly to C code. We have no problems with it.

**Comment by finmod** [comment]
See https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/issues/109 and also https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/issues/108 

You could use standard toy models from JuliaDiffEq and JuliaDynamics making sure that they are medium-sized problems.
